version: "3.9"
services:
  web1:
    build: app1
    ports:
      - "5000:5000"
  web2:
    build: app2
    ports:
      - "5001:5001"
    links:
      - "web1:app1.app1.svc.cluster.local"
  redis:
    image: "redis:alpine"
